ExamChapter 7 Assessment - CPATime left: 08:02

1. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    
    using namespace std;
    
    int main() {
        try {
            throw 2./4;
        }
        catch(int i) {
            cout << i;
        }
        return 0;
    }
 
Select correct answer (single choice)
 It prints 0 
 It prints 0.5 
 Compilation fails 
 Execution fails 

2. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    
    using namespace std;
    
    int main() {
        try {
            throw exception();
        }
        catch(exception &x) {
            cout << x.what();
        }
        return 0;
    }
 

Select correct answer (single choice)
 It prints an empty string 
 It prints a non-empty string 
 Execution fails 
 Compilation fails 

3. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    
    using namespace std;
    
    int main() {
        try {
            throw 3.14;
        }
        catch(double x) {
            x *= 2;
        }
        cout << x;
        return 0;
    }
 

Select correct answer (single choice)
 It prints a non-empty string 
 Compilation fails 
 Execution fails 
 It prints an empty string 

4. What happens when you attempt to compile and run the following code?

    #include <iostream>
    using namespace std;
    class X {
    public:
        X(void) { cout << 1; }
        ~X(void) { cout << 2; }
    };        
    X *exec() {
        X *x = new X();
        throw string("0");
        return x;
    }
    
    int main(void) {
        X *x;
        try {
            delete exec();
        } catch(string &s) {
            cout << s;
        }
        return 0;
    }
 

Select correct answer (single choice)
 Compilation fails 
 It prints 10 
 Execution fails 
 It prints 12 

5. What happens when you attempt to compile and run the following code?

    #include <iostream>
    using namespace std;
    class X {
    public:
        X(void) { cout << 0; }
        ~X(void) { cout << 2; }
    };        
    
    int main(void) {
        try {
            X *x = new X();
        throw true;
            delete x;
        } catch(bool s) {
            cout << s;
        }
        return 0;
    }
 

Select correct answer (single choice)
 Compilation fails 
 Execution fails 
 It prints 01 
 It prints 021 

6. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    #include <stdexcept>
    using namespace std;
    
    class X : public logic_error {
    public:
        X() : logic_error("0") {};
    };
    
    void z() throw(X) {
        throw new logic_error("0");
    }
    
    int main(void) {
        X x;
        try {
            z();
        } catch(X &i) {
            cout << i.what();
        }
        return 0;
    }
 

Select correct answer (single choice)
 It prints 102 
 Execution fails 
 It prints 120 
 Compilation fails 

7. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    #include <stdexcept>
    using namespace std;
    
    class E {};
    
    class X {
        static int c;
    public:
        X() { if(c++ > 2) throw new E; }
        ~X() { if(c++ > 2) throw new E; }
    };
    
    int X::c = 0;
    
    void f(int i) {
        X a,b;
        cout << i;
    }
    
    int main(void) {
        try {
            f(0);
            f(1);
        } catch(...) {
            cout << 1;
        }
        return 0;
    }
 

Select correct answer (single choice)
 Execution fails 
 It prints 0 
 Compilation fails 
 It prints 01 

8. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    #include <stdexcept>
    using namespace std;
    
    class E {};
    
    void f(int i) {
        E e;
        switch(i) {
        case 0 : throw e;
        case 1 : throw &e;
        }
        cout << 0;
    }
    
    int main(void) {
        try {
            f(2);
        } catch(E*) {
            cout << 1;
        } catch(E) {
            cout << 2;
        }
        return 0;
    }
 

Select correct answer (single choice)
 It prints 1 
 It prints 2 
 Compilation fails 
 It prints 0 

9. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    #include <stdexcept>
    using namespace std;
    
    class Int {
    public:
        int v;
        Int(int a) : v(a) {}
    };
    
    void a() {
        throw Int(1);
    }
    
    void b() {
        try {
            a();
        } catch(Int &i) {
            throw Int(i.v + 1);
        }
    }
    
    void c() {
        try {
            b();
        } catch(...) {
            throw;
        }
    }
    
    int main(void) {
        try {
            c();
        } catch(Int &i) {
            cout << i.v;
        }
        return 0;
    }
 

Select correct answer (single choice)
 It prints 0 
 It prints 1 
 Compilation fails 
 It prints 2 

10. What happens when you attempt to compile and run the following code?

    #include <iostream>
    #include <exception>
    #include <stdexcept>
    using namespace std;
    
    class Int {
    public:
        int v;
        Int(int a) : v(a) {}
    };
    
    void a() {
        throw 0;
    }
    
    void b() {
        try {
            a();
        } catch(int i) {
            throw Int(i + 1);
        }
    }
    
    void c() {
        try {
            b();
        } catch(...) {
            throw;
        }
    }
    
    int main(void) {
        try {
            c();
        } catch(Int &i) {
            cout << i.v;
        }
        return 0;
    }
 

Select correct answer (single choice)
 It prints 2 
 It prints 1 
 Compilation fails 
 It prints 0 

          
My Answer : 90%
1. Execution fails
2. It prints a non-empty string
3. Compilation fails
4. 10
5. 01
6. Execution fails
7. Execution fails
8. 0
9. 2
10. 1

